# Generated by Django 5.2.8 on 2026-01-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_theme_effects_and_animations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theme',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('new_year', 'New Year'), ('valentine', "Valentine's Day"), ('easter', 'Easter'), ('halloween', 'Halloween'), ('thanksgiving', 'Thanksgiving'), ('christmas', 'Christmas'), ('cny', 'Chinese New Year'), ('default', 'Default')], max_length=20),
        ),
    ]
