# Generated by Django 4.2.16 on 2026-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_projectimage_model'),
    ]

    operations = [
        # project_type column already exists in DB — skip AddField
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails/'),
        ),
    ]
