# Generated by Django 4.2.16 on 2026-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_projectimage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('live', 'Live Site / Web App'), ('local', 'Local Project / Gallery')], default='live', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails/'),
        ),
    ]
