# Generated by Django 4.2.16 on 2026-07-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_certificatefile_remove_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatefile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('word', 'Word')], default='image', max_length=10),
        ),
        # project_type already exists in the DB (added before migration tracking).
        # Record it in state only so future makemigrations stays clean.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='project_type',
                    field=models.CharField(
                        choices=[('live', 'Live Site / Web App'), ('local', 'Local Project / Gallery')],
                        default='live',
                        max_length=20,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
